version: 2.1
jobs:
  test:
    parameters:
      version:
        type: string
        default: latest

    docker:
      - image: circleci/python:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name:
          command: |
            sudo pip3 install --upgrade pip
            sudo pip3 install pipenv
            pipenv lock

      # Download and cache dependencies
      - restore_cache:
          keys:
            - venv-<< parameters.version >>-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - venv-<< parameters.version >>-

      - run:
          name: install dependencies
          command: |
            PIPENV_VENV_IN_PROJECT="enabled" pipenv install --dev

      - save_cache:
          paths:
            - ./.venv
          key: venv-<< parameters.version >>-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            pipenv run pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run:
          name: install python dependencies
          command: |
            sudo pip3 install --upgrade pip
            sudo pip3 install pipenv
            PIPENV_VENV_IN_PROJECT="enabled" pipenv install --dev

      - run:
          name: create package
          command: |
            source ./.venv/bin/activate
            python setup.py sdist bdist_wheel

      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers=" >> ~/.pypirc
            echo -e "    pypi" >> ~/.pypirc
            echo -e "    testpypi" >> ~/.pypirc
            echo -e "[testpypipypi]" >> ~/.pypirc
            echo -e "    username: nickswiss" >> ~/.pypirc
            echo -e "    password: $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: upload to pypi
          command: |
            source ./.venv/bin/activate
            twine upload --repository testpypi dist/*


workflows:
 tests:
   jobs:
     - test:
         name: "test-3.5"
         version: "3.5"
     - test:
         name: "test-3.6"
         version: "3.6"
     - test:
         name: "test-3.7"
         version: "3.7"
     - deploy:
         requires:
           - test-3.7
         filters:
           tags:
             only: /[0-9]+(\.[0-9]+)(\.[0-9]+)/
